name: cctv-viewer
version: '0.1.7+git'
summary: Viewer and mounter video streams
description: |
  CCTV Viewer - a simple application for simultaneously viewing multiple
  video streams. Designed for easy grid-based layout video streaming.
  Based on QtAV and ffmpeg.

icon: res/icons/cctv-viewer.svg
license: GPL-3.0

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  #- build-on: i386 # Not supported by core20
  - build-on: ppc64el
  - build-on: s390x

apps:
  cctv-viewer:
    command: bin/desktop-launch $SNAP/usr/bin/cctv-viewer
    desktop: usr/share/applications/cctv-viewer.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - mir
      - opengl
      - audio-playback
      - unity7  # Possibly unneeded
      - removable-media
      - network

parts:
  cctv-viewer:
    after: [desktop-qt5]
    plugin: cmake
    source: .
    override-pull: |
      snapcraftctl pull
      # Point icon to the correct location
      sed -i.bak -i -e 's|Icon=cctv-viewer|Icon=/usr/share/pixmaps/cctv-viewer.svg|g' cctv-viewer.desktop
    build-packages:
      - build-essential
      - libavformat-dev
      - libavcodec-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
      - libavdevice-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev
      - qttools5-dev
    stage-packages:
      - libslang2
      - libglu1-mesa
      - libavformat58
      - libavcodec58
      - libavutil56
      - libswscale5
      - libswresample3
      - libavdevice58
      - libqt5multimedia5
      - libqt5multimediaquick5
      - qml-module-qtquick-layouts
      - qml-module-qtqml-models2
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qml-module-qtquick-window2
      - qml-module-qtquick-dialogs
      - qml-module-qt-labs-settings
      - qml-module-qtmultimedia

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
